.TH "_TMR_OBJ_STRUCT" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_TMR_OBJ_STRUCT
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "volatile bool \fBtimerElapsed\fP"
.br
.ti -1c
.RI "volatile uint8_t \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Section: Data Type Definitions TMR Driver Hardware Instance Object
.PP
@Summary Defines the object required for the maintenance of the hardware instance\&.
.PP
@Description This defines the object required for the maintenance of the hardware instance\&. This object exists once per hardware instance of the peripheral\&.
.PP
Remarks: None\&. 
.PP
Definition at line 76 of file tmr2\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
