.TH "baseSW.h" 3 "Thu Feb 25 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baseSW.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stateTaskHandler\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstateTaskList\fP * \fBbaseSW_Initialize\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBstateTaskList\fP* baseSW_Initialize (void)"

.PP
Definition at line 559 of file baseSW\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
