.TH "BS_DATA_OBJ" 3 "Thu Feb 25 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BS_DATA_OBJ
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBheatProfileID\fP:5"
.br
.ti -1c
.RI "   uint8_t \fBstartHeating\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBstopHeating\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBsetHeatProfile\fP:1"
.br
.ti -1c
.RI "} \fBproperties\fP"
.br
.ti -1c
.RI "uint8_t \fBraw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 239 of file baseSW\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t heatProfileID"

.PP
Definition at line 241 of file baseSW\&.c\&.
.SS "struct { \&.\&.\&. }  properties"

.SS "uint8_t raw"

.PP
Definition at line 246 of file baseSW\&.c\&.
.SS "uint8_t setHeatProfile"

.PP
Definition at line 244 of file baseSW\&.c\&.
.SS "uint8_t startHeating"

.PP
Definition at line 242 of file baseSW\&.c\&.
.SS "uint8_t stopHeating"

.PP
Definition at line 243 of file baseSW\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
