.TH "RO_firmware_v1.X Directory Reference" 3 "Mon Apr 5 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RO_firmware_v1.X Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbaseSW\&.c\fP"
.br
.ti -1c
.RI "file \fBbaseSW\&.h\fP"
.br
.ti -1c
.RI "file \fBEEPROM_driver\&.c\fP"
.br
.ti -1c
.RI "file \fBEEPROM_driver\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBpiclib30_wrapper\&.h\fP"
.br
.ti -1c
.RI "file \fBstateTaskHandler\&.c\fP"
.br
.ti -1c
.RI "file \fBstateTaskHandler\&.h\fP"
.br
.in -1c
