.TH "C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files Directory Reference" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclock\&.c\fP"
.br
.ti -1c
.RI "file \fBclock\&.h\fP"
.br
.ti -1c
.RI "file \fBi2c1\&.c\fP"
.br
.ti -1c
.RI "file \fBi2c1\&.h\fP"
.br
.ti -1c
.RI "file \fBinterrupt_manager\&.c\fP"
.br
.ti -1c
.RI "file \fBinterrupt_manager\&.h\fP"
.br
.ti -1c
.RI "file \fBmcc\&.c\fP"
.br
.ti -1c
.RI "file \fBmcc\&.h\fP"
.br
.ti -1c
.RI "file \fBpin_manager\&.c\fP"
.br
.ti -1c
.RI "file \fBpin_manager\&.h\fP"
.br
.ti -1c
.RI "file \fBspi1\&.c\fP"
.br
.ti -1c
.RI "file \fBspi1\&.h\fP"
.br
.ti -1c
.RI "file \fBsystem\&.c\fP"
.br
.ti -1c
.RI "file \fBsystem\&.h\fP"
.br
.ti -1c
.RI "file \fBtmr2\&.c\fP"
.br
.ti -1c
.RI "file \fBtmr2\&.h\fP"
.br
.ti -1c
.RI "file \fBtraps\&.c\fP"
.br
.ti -1c
.RI "file \fBtraps\&.h\fP"
.br
.ti -1c
.RI "file \fBuart1\&.c\fP"
.br
.ti -1c
.RI "file \fBuart1\&.h\fP"
.br
.ti -1c
.RI "file \fBuart2\&.c\fP"
.br
.ti -1c
.RI "file \fBuart2\&.h\fP"
.br
.in -1c
