.TH "C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/clock.c" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/clock.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'xc\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCLOCK_Initialize\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void CLOCK_Initialize (void)"
@Generated PIC24 / dsPIC33 / PIC32MM MCUs Source File
.PP
@Company: Microchip Technology Inc\&.
.PP
@File Name: \fBclock\&.c\fP
.PP
@Summary: This is the \fBclock\&.c\fP file generated using PIC24 / dsPIC33 / PIC32MM MCUs
.PP
@Description: This header file provides implementations for driver APIs for all modules selected in the GUI\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702 The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 
.PP
Definition at line 49 of file clock\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
