.TH "HEAT_TIMER_OBJ" 3 "Mon Apr 5 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HEAT_TIMER_OBJ
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBHEAT_TIMER_STATUS\fP \fBstatus\fP"
.br
.ti -1c
.RI "uint16_t \fBtimeStamp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 335 of file baseSW\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBHEAT_TIMER_STATUS\fP status"

.PP
Definition at line 336 of file baseSW\&.c\&.
.SS "uint16_t timeStamp"

.PP
Definition at line 337 of file baseSW\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
