.TH "C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/i2c1.h" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/i2c1.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <xc\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBI2C1_TRANSACTION_REQUEST_BLOCK\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBI2C1_MESSAGE_STATUS\fP { \fBI2C1_MESSAGE_FAIL\fP, \fBI2C1_MESSAGE_PENDING\fP, \fBI2C1_MESSAGE_COMPLETE\fP, \fBI2C1_STUCK_START\fP, \fBI2C1_MESSAGE_ADDRESS_NO_ACK\fP, \fBI2C1_DATA_NO_ACK\fP, \fBI2C1_LOST_STATE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBI2C1_Initialize\fP (void)"
.br
.ti -1c
.RI "void \fBI2C1_MasterWrite\fP (uint8_t *pdata, uint8_t length, uint16_t address, \fBI2C1_MESSAGE_STATUS\fP *pstatus)"
.br
.ti -1c
.RI "void \fBI2C1_MasterRead\fP (uint8_t *pdata, uint8_t length, uint16_t address, \fBI2C1_MESSAGE_STATUS\fP *pstatus)"
.br
.ti -1c
.RI "void \fBI2C1_MasterTRBInsert\fP (uint8_t count, \fBI2C1_TRANSACTION_REQUEST_BLOCK\fP *ptrb_list, \fBI2C1_MESSAGE_STATUS\fP *pflag)"
.br
.ti -1c
.RI "void \fBI2C1_MasterReadTRBBuild\fP (\fBI2C1_TRANSACTION_REQUEST_BLOCK\fP *ptrb, uint8_t *pdata, uint8_t length, uint16_t address)"
.br
.ti -1c
.RI "void \fBI2C1_MasterWriteTRBBuild\fP (\fBI2C1_TRANSACTION_REQUEST_BLOCK\fP *ptrb, uint8_t *pdata, uint8_t length, uint16_t address)"
.br
.ti -1c
.RI "bool \fBI2C1_MasterQueueIsEmpty\fP (void)"
.br
.ti -1c
.RI "bool \fBI2C1_MasterQueueIsFull\fP (void)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBI2C1_MESSAGE_STATUS\fP"
I2C1 Generated Driver API Header File
.PP
@Company Microchip Technology Inc\&.
.PP
@File Name \fBi2c1\&.h\fP
.PP
@Summary This is the generated header file for the I2C1 driver using PIC24 / dsPIC33 / PIC32MM MCUs
.PP
@Description This header file provides APIs for driver for I2C1\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702
.PP
The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 Section: Included Files Section: Data Type Definitions I2C Driver Message Status Type Enumeration
.PP
@Summary Defines the different message status when processing TRBs\&.
.PP
@Description This type enumeration specifies the different types of status that an i2c request will have\&. For every submission of an i2c transaction, the status of that transaction is available\&. Based on the status, new transactions can be requested to the driver or a recovery can be performed to resend the transaction\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fII2C1_MESSAGE_FAIL \fP\fP
.TP
\fB\fII2C1_MESSAGE_PENDING \fP\fP
.TP
\fB\fII2C1_MESSAGE_COMPLETE \fP\fP
.TP
\fB\fII2C1_STUCK_START \fP\fP
.TP
\fB\fII2C1_MESSAGE_ADDRESS_NO_ACK \fP\fP
.TP
\fB\fII2C1_DATA_NO_ACK \fP\fP
.TP
\fB\fII2C1_LOST_STATE \fP\fP
.PP
Definition at line 84 of file i2c1\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void I2C1_Initialize (void)"
Section: Interface Routines @Summary Initializes the I2C instance : 1
.PP
@Description This routine initializes the i2c1 driver instance for : 1 index, making it ready for clients to open and use it\&. This routine must be called before any other I2C1 routine is called\&. This routine should only be called once during system initialization\&.
.PP
@Preconditions None\&.
.PP
@Param None\&.
.PP
@Returns None\&.
.PP
@Example \fC #define SLAVE_I2C_GENERIC_RETRY_MAX 100 #define SLAVE_I2C_GENERIC_DEVICE_TIMEOUT 50 // define slave timeout\fP
.PP
\fCinitialize the module \fBI2C1_Initialize()\fP;\fP
.PP
\fCwrite to an EEPROM Device 
.PP
.nf
    uint16_t        dataAddress;
    uint8_t         sourceData[16] = {  0xA0, 0xA1, 0xA2, 0xA3, 
                                        0xA4, 0xA5, 0xA6, 0xA7, 
                                        0xA8, 0xA9, 0xAA, 0xAB, 
                                        0xAC, 0xAD, 0xAE, 0xAF }; 
    uint8_t         *pData;
    uint16_t        nCount;

    uint8_t         writeBuffer[3];
    uint8_t         *pD;
    uint16_t        counter, timeOut, slaveTimeOut;

    I2C1_MESSAGE_STATUS status = I2C1_MESSAGE_PENDING;

    dataAddress = 0x10;             // starting EEPROM address 
    pD = sourceData;                // initialize the source of the data
    nCount = 16;                    // number of bytes to write

    for (counter = 0; counter < nCount; counter++)
    {

.fi
.PP
 build the write buffer first starting address of the EEPROM memory writeBuffer[0] = (dataAddress >> 8); // high address writeBuffer[1] = (uint8_t)(dataAddress); // low low address\fP
.PP
\fCdata to be written writeBuffer[2] = *pD++;\fP
.PP
\fCNow it is possible that the slave device will be slow\&. As a work around on these slaves, the application can retry sending the transaction timeOut = 0; slaveTimeOut = 0;\fP
.PP
\fC while(status != I2C1_MESSAGE_FAIL) { write one byte to EEPROM (3 is the number of bytes to write) I2C1_MasterWrite( writeBuffer, 3, slaveDeviceAddress, &status);\fP
.PP
\fCwait for the message to be sent or status has changed\&. while(status == I2C1_MESSAGE_PENDING) { add some delay here\fP
.PP
\fCtimeout checking check for max retry and skip this byte if (slaveTimeOut == SLAVE_I2C_GENERIC_DEVICE_TIMEOUT) break; else slaveTimeOut++; } if ((slaveTimeOut == SLAVE_I2C_GENERIC_DEVICE_TIMEOUT) || (status == I2C1_MESSAGE_COMPLETE)) break;\fP
.PP
\fCif status is I2C1_MESSAGE_ADDRESS_NO_ACK, or I2C1_DATA_NO_ACK, The device may be busy and needs more time for the last write so we can retry writing the data, this is why we use a while loop here\fP
.PP
\fCcheck for max retry and skip this byte if (timeOut == SLAVE_I2C_GENERIC_RETRY_MAX) break; else timeOut++; }\fP
.PP
\fC if (status == I2C1_MESSAGE_FAIL) { break; } dataAddress++;\fP
.PP
\fC }\fP
.PP
\fC \fP
.PP
Section: Driver Interface 
.PP
Definition at line 196 of file i2c1\&.c\&.
.SS "bool I2C1_MasterQueueIsEmpty (void)"

.PP
.nf
@Summary
    This function returns the empty status of the Master
    queue.

@Description
    This function returns the empty status of the Master
    queue. Use this function to check if the queue is empty.
    This can verify if the Master is currently idle.

@Preconditions
    None

@Param
    None

@Returns
    True if the queue is empty and false if the queue is not empty.

@Example
    <code>
        #define MCHP24AA512_ADDRESS    0x50 // slave device address

.fi
.PP
 check until queue is empty while(\fBI2C1_MasterQueueIsEmpty()\fP == false);
.PP
now send more data (assume readBuffer is initialized) I2C1_MasterRead( readBuffer, 3, MCHP24AA512_ADDRESS, &status); 
.br

.PP
Definition at line 707 of file i2c1\&.c\&.
.SS "bool I2C1_MasterQueueIsFull (void)"

.PP
.nf
@Summary
    This function returns the full status of the Master
    queue.

@Description
    This function returns the full status of the Master
    queue. Use this function to check if the queue is full.
    This can verify if the Master will not be able to accept
    addition transactions.

@Preconditions
    None

@Param
    None

@Returns
    True if the queue is full and false if the queue is not full.

@Example
    <code>
        #define MCHP24AA512_ADDRESS    0x50 // slave device address

.fi
.PP
 check until queue has space while(\fBI2C1_MasterQueueIsFull()\fP == true);
.PP
now send more data (assume readBuffer is initialized) I2C1_MasterRead( readBuffer, 3, MCHP24AA512_ADDRESS, &status);  
.PP
Definition at line 712 of file i2c1\&.c\&.
.SS "void I2C1_MasterRead (uint8_t * pdata, uint8_t length, uint16_t address, \fBI2C1_MESSAGE_STATUS\fP * pstatus)"

.PP
.nf
@Summary
    Handles one i2c master read transaction with the
    supplied parameters.

@Description
    This function prepares a TRB, then inserts it on the i2c queue.
    Finally, it waits for the transaction to complete and returns
    the result.

@Preconditions
    None

@Param
    address - The address of the i2c peripheral to be accessed

@Param
    length - The length of the data block to be sent

@Param
     pdata - A pointer to the memory location where received data will
             be stored

@Param
     pstatus - A pointer to the status variable that the i2c driver
        updates during the execution of the message.

@Returns
    I2C1_MESSAGE_STATUS

@Example
    <code>

        #define MCHP24AA512_RETRY_MAX       100  // define the retry count
        #define MCHP24AA512_ADDRESS         0x50 // slave device address
        #define MCHP24AA512_DEVICE_TIMEOUT  50   // define slave timeout 


        uint8_t MCHP24AA512_Read(
                                        uint16_t address,
                                        uint8_t *pData,
                                        uint16_t nCount)
        {
            I2C1_MESSAGE_STATUS status;
            uint8_t     writeBuffer[3];
            uint16_t    retryTimeOut, slaveTimeOut;
            uint16_t    counter;
            uint8_t     *pD;

            pD = pData;

            for (counter = 0; counter < nCount; counter++)
            {

.fi
.PP
 build the write buffer first starting address of the EEPROM memory writeBuffer[0] = (address >> 8); // high address writeBuffer[1] = (uint8_t)(address); // low low address
.PP
Now it is possible that the slave device will be slow\&. As a work around on these slaves, the application can retry sending the transaction retryTimeOut = 0; slaveTimeOut = 0;
.PP
while(status != I2C1_MESSAGE_FAIL) { write one byte to EEPROM (2 is the count of bytes to write) I2C1_MasterWrite( writeBuffer, 2, MCHP24AA512_ADDRESS, &status);
.PP
wait for the message to be sent or status has changed\&. while(status == I2C1_MESSAGE_PENDING) { add some delay here
.PP
timeout checking check for max retry and skip this byte if (slaveTimeOut == MCHP24AA512_DEVICE_TIMEOUT) return (0); else slaveTimeOut++; }
.PP
if (status == I2C1_MESSAGE_COMPLETE) break;
.PP
if status is I2C1_MESSAGE_ADDRESS_NO_ACK, or I2C1_DATA_NO_ACK, The device may be busy and needs more time for the last write so we can retry writing the data, this is why we use a while loop here
.PP
check for max retry and skip this byte if (retryTimeOut == MCHP24AA512_RETRY_MAX) break; else retryTimeOut++; }
.PP
if (status == I2C1_MESSAGE_COMPLETE) {
.PP
this portion will read the byte from the memory location\&. retryTimeOut = 0; slaveTimeOut = 0;
.PP
while(status != I2C1_MESSAGE_FAIL) { write one byte to EEPROM (2 is the count of bytes to write) I2C1_MasterRead( pD, 1, MCHP24AA512_ADDRESS, &status);
.PP
wait for the message to be sent or status has changed\&. while(status == I2C1_MESSAGE_PENDING) { add some delay here
.PP
timeout checking check for max retry and skip this byte if (slaveTimeOut == MCHP24AA512_DEVICE_TIMEOUT) return (0); else slaveTimeOut++; }
.PP
if (status == I2C1_MESSAGE_COMPLETE) break;
.PP
if status is I2C1_MESSAGE_ADDRESS_NO_ACK, or I2C1_DATA_NO_ACK, The device may be busy and needs more time for the last write so we can retry writing the data, this is why we use a while loop here
.PP
check for max retry and skip this byte if (retryTimeOut == MCHP24AA512_RETRY_MAX) break; else retryTimeOut++; } }
.PP
exit if the last transaction failed if (status == I2C1_MESSAGE_FAIL) { return(0); break; }
.PP
pD++; address++;
.PP
} return(1);
.PP
}
.PP
.PP
.nf
 </code>
.fi
.PP
 
.PP
Definition at line 611 of file i2c1\&.c\&.
.SS "void I2C1_MasterReadTRBBuild (\fBI2C1_TRANSACTION_REQUEST_BLOCK\fP * ptrb, uint8_t * pdata, uint8_t length, uint16_t address)"
@Summary This function populates a trb supplied by the calling function with the parameters supplied by the calling function\&.
.PP
@Description All i2c requests are in the form of TRB's\&. This helper function takes standard parameters and correctly formats the TRB\&. The R/W bit is set to ensure that the resulting TRB describes an i2c read operation\&.
.PP
This function does not send the transaction\&. To send the transaction, the TRB insert function (\fBI2C1_MasterTRBInsert()\fP) must be called\&.
.PP
@Preconditions None
.PP
@Param ptrb - A pointer to a caller supplied TRB\&.
.PP
@Param pdata - A pointer to the block of data to be received
.PP
@Param length - The length of the data block to be received
.PP
@Param address - The address of the i2c peripheral to be accessed
.PP
@Returns None
.PP
@Example \fC Refer to \fBI2C1_MasterTRBInsert()\fP for an example 
.br
 \fP 
.PP
Definition at line 683 of file i2c1\&.c\&.
.SS "void I2C1_MasterTRBInsert (uint8_t count, \fBI2C1_TRANSACTION_REQUEST_BLOCK\fP * ptrb_list, \fBI2C1_MESSAGE_STATUS\fP * pflag)"

.PP
.nf
@Summary
    Inserts a list of i2c transaction requests into the i2c
    transaction queue.

@Description
    The i2c processes lists of transaction requests.  Each transaction
    list is handled as a string of i2c restarts.  When the list of
    transactions is complete, an i2c stop is produced, the flag is set
    with the correct condition code and the next list is processed
    from the queue.

    This function inserts lists of requests prepared by the user
    application into the queue along with a pointer to the completion
    flag.

    The transaction is inserted into the list only if there is space
    in the list. If there is no space, the function exits with the
    flag set to I2C1_MESSAGE_FAIL.

@Preconditions
    None

@Param
    count - The numer of transaction requests in the trb_list.

@Param
     ptrb_list - A pointer to an array of transaction requests (TRB).
        See I2C1_TRANSACTION_REQUEST_BLOCK definition for details.

@Param
     pflag - A pointer to a completion flag.

@Returns
    None

@Example
    <code>


        uint8_t EMULATED_EEPROM_Read(
                                       uint16_t slaveDeviceAddress,
                                       uint16_t dataAddress,
                                       uint8_t *pData,
                                       uint16_t nCount)
        {
            I2C1_MESSAGE_STATUS status;
            I2C1_TRANSACTION_REQUEST_BLOCK readTRB[2];
            uint8_t     writeBuffer[3];
            uint16_t    timeOut, slaveTimeOut;

.fi
.PP
 this initial value is important status = I2C1_MESSAGE_PENDING;
.PP
build the write buffer first starting address of the EEPROM memory writeBuffer[0] = (dataAddress >> 8); // high address writeBuffer[1] = (uint8_t)(dataAddress); // low low address
.PP
we need to create the TRBs for a random read sequence to the EEPROM Build TRB for sending address I2C1_MasterWriteTRBBuild( &readTRB[0], writeBuffer, 2, slaveDeviceAddress); Build TRB for receiving data I2C1_MasterReadTRBBuild( &readTRB[1], pData, nCount, slaveDeviceAddress);
.PP
timeOut = 0; slaveTimeOut = 0;
.PP
while(status != I2C1_MESSAGE_FAIL) { now send the transactions I2C1_MasterTRBInsert(2, readTRB, &status);
.PP
wait for the message to be sent or status has changed\&. while(status == I2C1_MESSAGE_PENDING) { add some delay here
.PP
timeout checking check for max retry and skip this byte if (slaveTimeOut == SLAVE_I2C_GENERIC_SLAVE_TIMEOUT) return (0); else slaveTimeOut++; }
.PP
if (status == I2C1_MESSAGE_COMPLETE) break;
.PP
if status is I2C1_MESSAGE_ADDRESS_NO_ACK, or I2C1_DATA_NO_ACK, The device may be busy and needs more time for the last write so we can retry writing the data, this is why we use a while loop here
.PP
check for max retry and skip this byte if (timeOut == SLAVE_I2C_GENERIC_RETRY_MAX) return (0); else timeOut++;
.PP
} return (1);
.PP
} 
.br

.PP
Definition at line 633 of file i2c1\&.c\&.
.SS "void I2C1_MasterWrite (uint8_t * pdata, uint8_t length, uint16_t address, \fBI2C1_MESSAGE_STATUS\fP * pstatus)"
@Summary Handles one i2c master write transaction with the supplied parameters\&.
.PP
@Description This function prepares a TRB, then inserts it on the i2c queue\&. Finally, it waits for the transaction to complete and returns the result\&.
.PP
@Preconditions None
.PP
@Param address - The address of the i2c peripheral to be accessed
.PP
@Param length - The length of the data block to be sent
.PP
@Param pdata - A pointer to the block of data to be sent
.PP
@Param pstatus - A pointer to the status variable that the i2c driver updates during the execution of the message\&.
.PP
@Returns I2C1_MESSAGE_STATUS
.PP
@Example \fC Refer to \fBI2C1_Initialize()\fP and \fBI2C1_MasterRead()\fP for an examples 
.br
 \fP 
.PP
Definition at line 590 of file i2c1\&.c\&.
.SS "void I2C1_MasterWriteTRBBuild (\fBI2C1_TRANSACTION_REQUEST_BLOCK\fP * ptrb, uint8_t * pdata, uint8_t length, uint16_t address)"
@Summary This function populates a trb supplied by the calling function with the parameters supplied by the calling function\&.
.PP
@Description All i2c requests are in the form of TRB's\&. This helper function takes standard parameters and correctly formats the TRB\&. The R/W bit is cleared to ensure that the resulting TRB describes an i2c write operation\&.
.PP
This function does not send the transaction\&. To send the transaction, the TRB insert function (\fBI2C1_MasterTRBInsert()\fP) must be called\&.
.PP
@Preconditions None
.PP
@Param ptrb - A pointer to a caller supplied TRB\&.
.PP
@Param pdata - A pointer to the block of data to be sent
.PP
@Param length - The length of the data block to be sent
.PP
@Param address - The address of the i2c peripheral to be accessed
.PP
@Returns None
.PP
@Example \fC Refer to \fBI2C1_MasterTRBInsert()\fP for an example 
.br
 \fP 
.PP
Definition at line 696 of file i2c1\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
