.TH "I2C_TR_QUEUE_STATUS" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_TR_QUEUE_STATUS
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBfull\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBempty\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBreserved\fP:6"
.br
.ti -1c
.RI "} \fBs\fP"
.br
.ti -1c
.RI "uint8_t \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
I2C1 Generated Driver File
.PP
@Company Microchip Technology Inc\&.
.PP
@File Name \fBi2c1\&.c\fP
.PP
@Summary This is the generated header file for the i2c1 driver using PIC24 / dsPIC33 / PIC32MM MCUs
.PP
@Description This header file provides APIs for driver for i2c1\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702
.PP
The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 Section: Data Types I2C Driver Queue Status Type
.PP
@Summary Defines the type used for the transaction queue status\&.
.PP
@Description This defines type used to keep track of the queue status\&. 
.PP
Definition at line 63 of file i2c1\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
