.TH "I2C_TR_QUEUE_ENTRY" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_TR_QUEUE_ENTRY
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBcount\fP"
.br
.ti -1c
.RI "\fBI2C1_TRANSACTION_REQUEST_BLOCK\fP * \fBptrb_list\fP"
.br
.ti -1c
.RI "I2C1_MESSAGE_STATUS * \fBpTrFlag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
I2C Driver Queue Entry Type
.PP
@Summary Defines the object used for an entry in the i2c queue items\&.
.PP
@Description This defines the object in the i2c queue\&. Each entry is a composed of a list of TRBs, the number of the TRBs and the status of the currently processed TRB\&. 
.PP
Definition at line 85 of file i2c1\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
