.TH "IC_MAX31855_DATA" 3 "Thu Feb 25 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IC_MAX31855_DATA
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fBthermocouple_temperature_data\fP:14"
.br
.ti -1c
.RI "   uint8_t \fBreserved1\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBfault\fP:1"
.br
.ti -1c
.RI "   uint16_t \fBinternal_temperature_data\fP:12"
.br
.ti -1c
.RI "   uint8_t \fBreserved2\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBscv\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBscg\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBoc\fP:1"
.br
.ti -1c
.RI "} \fBs\fP"
.br
.ti -1c
.RI "uint32_t \fBrawData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 170 of file baseSW\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t fault"

.PP
Definition at line 176 of file baseSW\&.c\&.
.SS "uint16_t internal_temperature_data"

.PP
Definition at line 177 of file baseSW\&.c\&.
.SS "uint8_t oc"

.PP
Definition at line 181 of file baseSW\&.c\&.
.SS "uint32_t rawData"

.PP
Definition at line 183 of file baseSW\&.c\&.
.SS "uint8_t reserved1"

.PP
Definition at line 175 of file baseSW\&.c\&.
.SS "uint8_t reserved2"

.PP
Definition at line 178 of file baseSW\&.c\&.
.SS "struct { \&.\&.\&. }  s"

.SS "uint8_t scg"

.PP
Definition at line 180 of file baseSW\&.c\&.
.SS "uint8_t scv"

.PP
Definition at line 179 of file baseSW\&.c\&.
.SS "uint16_t thermocouple_temperature_data"

.PP
Definition at line 174 of file baseSW\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
