.TH "C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/interrupt_manager.c" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/interrupt_manager.c
.SH SYNOPSIS
.br
.PP
\fC#include <xc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBINTERRUPT_Initialize\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void INTERRUPT_Initialize (void)"
System Interrupts Generated Driver File
.PP
@Company: Microchip Technology Inc\&.
.PP
@File Name: \fBinterrupt_manager\&.h\fP
.PP
@Summary: This is the generated driver implementation file for setting up the interrupts using PIC24 / dsPIC33 / PIC32MM MCUs
.PP
@Description: This source file provides implementations for PIC24 / dsPIC33 / PIC32MM MCUs interrupts\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702 The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 Section: Includes void INTERRUPT_Initialize (void) 
.PP
Definition at line 53 of file interrupt_manager\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
