.TH "main.c" 3 "Mon Apr 5 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mcc_generated_files/system\&.h'\fP
.br
\fC#include 'mcc_generated_files/pin_manager\&.h'\fP
.br
\fC#include 'mcc_generated_files/i2c1\&.h'\fP
.br
\fC#include 'stateTaskHandler\&.h'\fP
.br
\fC#include 'baseSW\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"
Generated \fBmain\&.c\fP file from MPLAB Code Configurator
.PP
@Company Microchip Technology Inc\&.
.PP
@File Name \fBmain\&.c\fP
.PP
@Summary This is the generated \fBmain\&.c\fP using PIC24 / dsPIC33 / PIC32MM MCUs\&.
.PP
@Description This source file provides main entry point for system initialization and application code development\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702 The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 Section: Included Files 
.PP
Definition at line 66 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
