.TH "C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/mcc.h" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/mcc.h
.SH SYNOPSIS
.br
.PP
\fC#include <xc\&.h>\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'pin_manager\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'i2c1\&.h'\fP
.br
\fC#include 'interrupt_manager\&.h'\fP
.br
\fC#include 'traps\&.h'\fP
.br
\fC#include 'uart1\&.h'\fP
.br
\fC#include 'uart2\&.h'\fP
.br
\fC#include 'tmr2\&.h'\fP
.br
\fC#include 'spi1\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
