.TH "piclib30_wrapper.h" 3 "Thu Feb 25 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piclib30_wrapper.h
.SH SYNOPSIS
.br
.PP
\fC#include <libpic30\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFCY\fP   4000000UL"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FCY   4000000UL"

.PP
Definition at line 15 of file piclib30_wrapper\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
