.TH "C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/pin_manager.c" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/pin_manager.c
.SH SYNOPSIS
.br
.PP
\fC#include <xc\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'pin_manager\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPIN_MANAGER_Initialize\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void PIN_MANAGER_Initialize (void)"
PIN MANAGER Generated Driver File
.PP
@Company: Microchip Technology Inc\&.
.PP
@File Name: \fBpin_manager\&.c\fP
.PP
@Summary: This is the generated manager file for the PIC24 / dsPIC33 / PIC32MM MCUs device\&. This manager configures the pins direction, initial state, analog setting\&. The peripheral pin select, PPS, configuration is also handled by this manager\&.
.PP
@Description: This source file provides implementations for PIN MANAGER\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702 The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 Section: Includes Section: Driver Interface Function Definitions 
.PP
Definition at line 59 of file pin_manager\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
