.TH "SENSOR_DATA" 3 "Mon Apr 5 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SENSOR_DATA \- Measuremnt data array structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIC_MAX31855_DATA\fP * \fBdataArrayQue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBisUploaded\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBcurrentData\fP:7"
.br
.ti -1c
.RI "} \fBdataArrayStatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Measuremnt data array structure\&. 

This structure holds a maximum of SENSOR_DATA_STORE_LENGTH measurements read from the temperature sensor\&. currentData data denotes the array index which will be overwritten is new data arrives from the sensor\&. This structure implements a ring buffer, so currentData only can be between 0 and SENSOR_DATA_STORE_LENGTH - 1\&. 
.PP
Definition at line 211 of file baseSW\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t currentData"
Ring buffer pointer 
.PP
Definition at line 215 of file baseSW\&.c\&.
.SS "\fBIC_MAX31855_DATA\fP* dataArrayQue"
Pointer to measurement data 
.PP
Definition at line 212 of file baseSW\&.c\&.
.SS "struct { \&.\&.\&. }  dataArrayStatus"
Measurement data status desriptor 
.SS "uint8_t isUploaded"
1 is all records are filled with measurement data in the ring buffer, otherwise 0\&. 
.br
 
.PP
Definition at line 214 of file baseSW\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
