.TH "SENSOR_DATA" 3 "Thu Feb 25 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SENSOR_DATA
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBIC_MAX31855_DATA\fP * \fBdataArrayQue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fBisUploaded\fP:1"
.br
.ti -1c
.RI "   uint8_t \fBcurrentData\fP:7"
.br
.ti -1c
.RI "} \fBdataArrayStatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 186 of file baseSW\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t currentData"

.PP
Definition at line 190 of file baseSW\&.c\&.
.SS "\fBIC_MAX31855_DATA\fP* dataArrayQue"

.PP
Definition at line 187 of file baseSW\&.c\&.
.SS "struct { \&.\&.\&. }  dataArrayStatus"

.SS "uint8_t isUploaded"

.PP
Definition at line 189 of file baseSW\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
