.TH "C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/system.h" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/system.h
.SH SYNOPSIS
.br
.PP
\fC#include 'xc\&.h'\fP
.br
\fC#include 'stdint\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_XTAL_FREQ\fP   8000000UL"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSYSTEM_Initialize\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _XTAL_FREQ   8000000UL"
@Generated PIC24 / dsPIC33 / PIC32MM MCUs Source File
.PP
@Company: Microchip Technology Inc\&.
.PP
@File Name: \fBsystem\&.h\fP
.PP
@Summary: This is the \fBsystem\&.h\fP file generated using PIC24 / dsPIC33 / PIC32MM MCUs
.PP
@Description: This header file provides implementations for driver APIs for all modules selected in the GUI\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702 The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 
.PP
Definition at line 46 of file system\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void SYSTEM_Initialize (void)"
@Param none @Returns none @Description Initializes the device to the default states configured in the MCC GUI @Example \fBSYSTEM_Initialize(void)\fP;
.PP
@Generated PIC24 / dsPIC33 / PIC32MM MCUs Source File
.PP
@Company: Microchip Technology Inc\&.
.PP
@File Name: \fBsystem\&.h\fP
.PP
@Summary: This is the sysetm\&.h file generated using PIC24 / dsPIC33 / PIC32MM MCUs
.PP
@Description: This header file provides implementations for driver APIs for all modules selected in the GUI\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702 The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 
.PP
Definition at line 108 of file system\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
