.TH "C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/system.c" 3 "Wed Feb 24 2021" "Version 1.0" "Reflow Oven" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/EDU_OBOS_5057/Documents/Reflow oven/Design/SW/RO_firmware_v1.X/mcc_generated_files/system.c
.SH SYNOPSIS
.br
.PP
\fC#include 'pin_manager\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'system\&.h'\fP
.br
\fC#include 'i2c1\&.h'\fP
.br
\fC#include 'interrupt_manager\&.h'\fP
.br
\fC#include 'traps\&.h'\fP
.br
\fC#include 'uart1\&.h'\fP
.br
\fC#include 'uart2\&.h'\fP
.br
\fC#include 'tmr2\&.h'\fP
.br
\fC#include 'spi1\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSYSTEM_Initialize\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void SYSTEM_Initialize (void)"
@Generated PIC24 / dsPIC33 / PIC32MM MCUs Source File
.PP
@Company: Microchip Technology Inc\&.
.PP
@File Name: \fBsystem\&.h\fP
.PP
@Summary: This is the sysetm\&.h file generated using PIC24 / dsPIC33 / PIC32MM MCUs
.PP
@Description: This header file provides implementations for driver APIs for all modules selected in the GUI\&. Generation Information : Product Revision : PIC24 / dsPIC33 / PIC32MM MCUs - 1\&.170\&.0 Device : PIC24FJ256GA702 The generated drivers are tested against the following: Compiler : XC16 v1\&.61 MPLAB : MPLAB X v5\&.45 
.PP
Definition at line 108 of file system\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven from the source code\&.
