.TH "TEMPERATURE_BUFFER" 3 "Mon Apr 5 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TEMPERATURE_BUFFER \- Reference temperature buffer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t * \fBdata\fP"
.br
.ti -1c
.RI "uint16_t * \fBtime\fP"
.br
.ti -1c
.RI "uint16_t \fBoffset\fP"
.br
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.ti -1c
.RI "uint8_t \fBvalid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reference temperature buffer\&. 

This temperature buffer structure conatins a 8 bit unsigned integer pointer, and an offset value\&. The offset used during memory operations or denotes the actual temperature reference (based on time) in the array depending on the context\&. 
.PP
Definition at line 124 of file baseSW\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t* data"
Buffer array pointer, temperature = data*4 
.PP
Definition at line 126 of file baseSW\&.c\&.
.SS "uint16_t offset"
Buffer offset value 
.PP
Definition at line 128 of file baseSW\&.c\&.
.SS "uint16_t size"
Number of records in the temperature buffer 
.PP
Definition at line 129 of file baseSW\&.c\&.
.SS "uint16_t* time"
Data time * 100[ms] 
.PP
Definition at line 127 of file baseSW\&.c\&.
.SS "uint8_t valid"
\fBTEMPERATURE_BUFFER\fP is valid is valid=0x1, invalid else 
.PP
Definition at line 130 of file baseSW\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
