.TH "TEMPERATURE_PROFILE" 3 "Mon Apr 5 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TEMPERATURE_PROFILE \- Reference temperature profile\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTEMPERATURE_BUFFER\fP \fBcurrentProfile\fP"
.br
.ti -1c
.RI "\fBTEMPERATURE_BUFFER\fP \fBbufferProfile\fP"
.br
.ti -1c
.RI "\fBTEMPERATURE_BUFFER\fP \fBdefaultProfile\fP"
.br
.ti -1c
.RI "\fBTEMPERATURE_BUFFER_STATUS\fP \fBprofileStatus\fP"
.br
.ti -1c
.RI "uint16_t \fBaddressBuffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reference temperature profile\&. 

Reference temperature profile three \fBTEMPERATURE_BUFFER\fP, a TEMPERATURE_BUFFER_STATUS and an addressBuffer\&. The addressBuffer is used to store the EEPROM address\&. Only bufferProfile can be used for memory operations, and currentProfile only can be used for heating processes\&. 
.PP
Definition at line 154 of file baseSW\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t addressBuffer"
This buffers stores the EEPROM address 
.PP
Definition at line 161 of file baseSW\&.c\&.
.SS "\fBTEMPERATURE_BUFFER\fP bufferProfile"
Buffer profile array pointer 
.PP
Definition at line 158 of file baseSW\&.c\&.
.SS "\fBTEMPERATURE_BUFFER\fP currentProfile"
Current profile array pointer 
.PP
Definition at line 157 of file baseSW\&.c\&.
.SS "\fBTEMPERATURE_BUFFER\fP defaultProfile"
Default profile buffer array pointer 
.PP
Definition at line 159 of file baseSW\&.c\&.
.SS "\fBTEMPERATURE_BUFFER_STATUS\fP profileStatus"
Temperature profile status 
.PP
Definition at line 160 of file baseSW\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
