.TH "TRANSCIEVE_OBJ" 3 "Mon Apr 5 2021" "Version 1.0" "Reflow Oven firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TRANSCIEVE_OBJ
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTRANSCIEVE_STATUS\fP \fBstatus\fP"
.br
.ti -1c
.RI "bool \fBNextionTransmissionInProgress\fP"
.br
.ti -1c
.RI "bool \fBFTDITransmissionInProgress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 316 of file baseSW\&.c\&.
.SH "Field Documentation"
.PP 
.SS "bool FTDITransmissionInProgress"

.PP
Definition at line 319 of file baseSW\&.c\&.
.SS "bool NextionTransmissionInProgress"

.PP
Definition at line 318 of file baseSW\&.c\&.
.SS "\fBTRANSCIEVE_STATUS\fP status"

.PP
Definition at line 317 of file baseSW\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reflow Oven firmware from the source code\&.
